### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Kaze1027** [gabuch2/L4D2-Laravel-Stats#1]
我跟着大佬的项目自己尝试进行了搭建，最后搭建好了发现访问只会出现500 | server error，如果可以，麻烦指导一下。
![image](https://github.com/gabuch2/L4D2-Laravel-Stats/assets/51438620/1aa48645-efa9-4be2-8c7e-db5e16cf58f4)

**Comment by gabuch2** [comment]
Hello. From what I understood from a machine translation I assume you tried to install it without success.

Like all Laravel projects, you need to run the following steps:

- Ensure your web server application supports rewrite. (for Apache just run `sudo a2enmod rewrite` and ensure the directive `AllowOverride` is set to `all` in the folder where the project is located, for nginx you need to investigate yourself because I don't use nginx) 
- `composer install` to install all the required dependencies.
- Configure the .env file with all the data required.

You can also use `php artisan serve` in the project directory to test if everything is working correctly. 

Note that it's been too long since I made this, so PHP8+ is not supported yet and it will crash instantly, probably this is the problem you're having? You need to use PHP7.3 (Last version where I confirmed it was working).

**Comment by Kaze1027** [comment]
Thank you for your reply, I've tried with php8.0 last night, now I'm ganna try it with php7.3.
I aim to make it worked with caddy ahead, caddy is listening to port 80/443, all the certified user will reverse to php page.
I'm trying now

**Comment by Kaze1027** [comment]
Does it support mysql 8.0

**Comment by Kaze1027** [comment]
Here comes a report:
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sname' in 'where clause' (SQL: select * from `server_settings` where `sname` = motdmessage limit 1) (View: /var/www/html/l4d2stats/resources/views/layout/app.blade.php)

![image](https://github.com/gabuch2/L4D2-Laravel-Stats/assets/51438620/73baf7a3-c6e3-4270-bee0-dbaf2d82d88c)

**Comment by Kaze1027** [comment]
Here comes a report:
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sname' in 'where clause' (SQL: select * from `server_settings` where `sname` = motdmessage limit 1) (View: /var/www/html/l4d2stats/resources/views/layout/app.blade.php)

![image](https://github.com/gabuch2/L4D2-Laravel-Stats/assets/51438620/73baf7a3-c6e3-4270-bee0-dbaf2d82d88c)

And this is my database in Mysql8.0
![image](https://github.com/gabuch2/L4D2-Laravel-Stats/assets/51438620/5f2e93d0-441f-4f43-9a2a-5b406eadbd08)

**Comment by gabuch2** [comment]
Are you using [Custom Player Stats](https://forums.alliedmods.net/showthread.php?t=115965) by muukis?

**Comment by Kaze1027** [comment]
> Are you using [Custom Player Stats](https://forums.alliedmods.net/showthread.php?t=115965) by muukis?

I'm planning to replace the plugin 'SRS' by it, but not installed yet.

**Comment by Kaze1027** [comment]
Thank you for your reply, I quit.
